apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: metrics-monitor
   labels:
      team: sa
spec:
   namespaceSelector:
      any: true
   selector:
      matchLabels:
        app: temporal-booking-worker
   endpoints:
      - port: metrics
