apiVersion: v1
kind: Service
metadata:
  labels:
    team: sa
    app: temporal-booking-worker
  name: metrics-svc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics  
  selector:
    app: temporal-booking-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
