---
apiVersion: v1
kind: Service
metadata:
  name: temporal-booking
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb   
  labels:
    app: temporal-booking
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    name: workflow
  selector:
    app: temporal-booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-booking
  template:
    metadata:
      labels:
        app: temporal-booking
    spec:
      containers:
      - name: worker
        image: ktenzer/temporal-booking-worker:v1.0
        imagePullPolicy: Always
        env:
        - name: TEMPORAL_HOST_URL
          value: temporal-booking.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_NAMESPACE
          value: temporal-booking.sdvdw
        - name: TEMPORAL_MTLS_TLS_CERT
          value: /etc/certs/tls.crt
        - name: TEMPORAL_MTLS_TLS_KEY
          value: /etc/certs/tls.key
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      - name: workflow
        image: ktenzer/temporal-booking-workflow:v1.0
        imagePullPolicy: Always
        ports:
        - name: workflow
          containerPort: 5000
        env:
        - name: TEMPORAL_HOST_URL
          value: temporal-booking.sdvdw.tmprl.cloud:7233
        - name: TEMPORAL_NAMESPACE
          value: temporal-booking.sdvdw
        - name: TEMPORAL_MTLS_TLS_CERT
          value: /etc/certs/tls.crt
        - name: TEMPORAL_MTLS_TLS_KEY
          value: /etc/certs/tls.key
        volumeMounts:
        - mountPath: /etc/certs
          name: certs
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: temporal-booking-tls-secret
